name: Docker Image CI

on: 
  deployment:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: make   # docker build . --file Dockerfile --tag my-image-name:$(date +%s)
